### ISSUE TITLE
Rubocop Disable does not work

### ISSUE THREAD

**Issue by miry** [m4i/rubocop-git#17]
Rubocop disable directives does not work for `rubocop-git`

```ruby
# rubocop:disable Rails/HasAndBelongsToMany
has_and_belongs_to_many :segments
# rubocop:enable Rails/HasAndBelongsToMany
```

Response:

```
app/models/model.rb:15:3: C: Rails/HasAndBelongsToMany: Prefer has_many :through to has_and_belongs_to_many.
  has_and_belongs_to_many :segments,
  ^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by nicollis** [comment]
You should bring this error up in the actual [Rubocop project](https://github.com/bbatsov/rubocop/issues). Rubocop-git extends the already existing rubocop gem. rubocop-git is not directly responsible for flagging errors.

**Comment by miry** [comment]
hm. rubocop is working fine for this. I supposed it is related how do you handle the comments.

**Comment by dkniffin** [comment]
FYI, this isn't currently resolved, but I just opened a PR #22 that resolves.

**Comment by llekn** [comment]
While I understand it might be a rubocop bug (or strange feature), this completely defeats rubocop-git purpose for me: I just can't trust rubocop-git to check my commits and have the same result as rubocop will output on a CI server.

@m4i @miry would you please consider merging PR #22 ? This would allow me to depend on rubocop-git again

**Comment by miry** [comment]
@llekn @dkniffin  I wish #22 would fix this issue. 👍

**Comment by m4i** [comment]
Thank you for your reporting.
Sorry for my late reply.
I have just released 0.1.3.

**Comment by llekn** [comment]
Thanks @m4i ! I've just tested this and it works great (for me at least)
:clap:

**Comment by llekn** [comment]
@m4i  I'm afraid that I replied too fast... 

While using `rubocop-git` now considers the `#rubocop:disable` flags  (it outputs `no offenses detected`) the return value is 1 which prevents me using it as a simple pre-commit git hook, since git expects the hook to return 0.

While I could fix this in the pre-commit hook script, I think the correct way would be to rubocop-git to return 0, as I would expect the same behavior as validating a "correct" file without `#rubocop:disable` flags.

Any thoughts on this?

**Comment by simonrand** [comment]
@llekn I've a commit on a fork of this repo which (crudely) patches this: https://github.com/simonrand/rubocop-git/commit/c6eb10a1c9e85e27b16a5e6a59571c132fe4bbff

**Comment by llekn** [comment]
hey @simonrand it works great for me!

It would be great if you make a PR to merge your fix.

**Comment by simonrand** [comment]
@llekn yes will try and do that at some point soon
